name: Tests

on:
  push:
    paths:
      - 'src/trendreview/*.py'
      - 'src/tests/*.py'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup python version 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi

      - name: Run tests using unittest
        run: |
          mkdir ./reports
          cd ./src
          python -m unittest discover tests --pattern test_*.py